CREATE DATABASE IF NOT EXISTS jokesapp;
USE jokesapp;

CREATE TABLE types (
    type VARCHAR(45) NOT NULL UNIQUE PRIMARY KEY
);


CREATE TABLE jokes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(45) NOT NULL,
    setup VARCHAR(200) NOT NULL,
    punchline VARCHAR(200) NOT NULL,
    FOREIGN KEY (type) REFERENCES types(type)
);

INSERT INTO types (type) VALUES
('any'), ('general'), ('knock-knock'), ('programming'), ('dad'), ('food');

INSERT INTO jokes (type, setup, punchline) VALUES
  ('general', 'What did the fish say when it hit the wall?', 'Dam.'),
  ('general', 'How do you make a tissue dance?', 'You put a little boogie on it.'),
  ('general', 'What''s Forrest Gump''s password?', '1Forrest1'),
  ('general', 'What do you call a belt made out of watches?', 'A waist of time.'),
  ('general', 'Why can''t bicycles stand on their own?', 'They are two tired'),
  ('general', 'How does a train eat?', 'It goes chew, chew'),
  ('general', 'What do you call a singing Laptop', 'A Dell'),
  ('general', 'How many lips does a flower have?', 'Tulips'),
  ('general', 'How do you organize an outer space party?', 'You planet'),
  ('general', 'What kind of shoes does a thief wear?', 'Sneakers'),
  ('general', 'What''s the best time to go to the dentist?', 'Tooth hurty.'),
  ('knock-knock', 'Knock knock. 
 Who''s there? 
 A broken pencil. 
 A broken pencil who?', 'Never mind. It''s pointless.'),
  ('knock-knock', 'Knock knock. 
 Who''s there? 
 Cows go. 
 Cows go who?', 'No, cows go moo.'),
  ('knock-knock', 'Knock knock. 
 Who''s there? 
 Little old lady. 
 Little old lady who?', 'I didn''t know you could yodel!'),
  ('programming', 'What''s the best thing about a Boolean?', 'Even if you''re wrong, you''re only off by a bit.'),
  ('programming', 'What''s the object-oriented way to become wealthy?', 'Inheritance'),
  ('programming', 'Where do programmers like to hangout?', 'The Foo Bar.'),
  ('programming', 'Why did the programmer quit his job?', 'Because he didn''t get arrays.'),
  ('general', 'Did you hear about the two silk worms in a race?', 'It ended in a tie.'),
  ('general', 'What do you call a laughing motorcycle?', 'A Yamahahahaha.'),
  ('general', 'A termite walks into a bar and says...', '''Where is the bar tended?'''),
  ('general', 'What does C.S. Lewis keep at the back of his wardrobe?', 'Narnia business!'),
  ('programming', 'Why do programmers always mix up Halloween and Christmas?', 'Because Oct 31 == Dec 25'),
  ('programming', 'A SQL query walks into a bar, walks up to two tables and asks...', '''Can I join you?'''),
  ('programming', 'How many programmers does it take to change a lightbulb?', 'None that''s a hardware problem'),
  ('programming', 'If you put a million monkeys at a million keyboards, one of them will eventually write a Java program', 'the rest of them will write Perl'),
  ('programming', '[''hip'', ''hip'']', '(hip hip array)'),
  ('programming', 'To understand what recursion is...', 'You must first understand what recursion is'),
  ('programming', 'There are 10 types of people in this world...', 'Those who understand binary and those who don''t'),
  ('general', 'What did the duck say when he bought lipstick?', 'Put it on my bill'),
  ('general', 'What happens to a frog''s car when it breaks down?', 'It gets toad away'),
  ('general', 'did you know the first French fries weren''t cooked in France?', 'they were cooked in Greece'),
  ('programming', 'Which song would an exception sing?', 'Can''t catch me - Avicii'),
  ('knock-knock', 'Knock knock. 
 Who''s there? 
 Opportunity.', 'That is impossible. Opportunity doesn’t come knocking twice!'),
  ('programming', 'Why do Java programmers wear glasses?', 'Because they don''t C#'),
  ('general', 'Why did the mushroom get invited to the party?', 'Because he was a fungi.'),
  ('general', 'Do you know what the word ''was'' was initially?', 'Before was was was was was is.'),
  ('general', 'I''m reading a book about anti-gravity...', 'It''s impossible to put down'),
  ('general', 'If you''re American when you go into the bathroom, and American when you come out, what are you when you''re in there?', 'European'),
  ('general', 'Want to hear a joke about a piece of paper?', 'Never mind...it''s tearable'),
  ('general', 'I just watched a documentary about beavers.', 'It was the best dam show I ever saw'),
  ('general', 'If you see a robbery at an Apple Store...', 'Does that make you an iWitness?'),
  ('general', 'A ham sandwhich walks into a bar and orders a beer. The bartender says...', 'I''m sorry, we don''t serve food here'),
  ('general', 'Why did the Clydesdale give the pony a glass of water?', 'Because he was a little horse'),
  ('general', 'If you boil a clown...', 'Do you get a laughing stock?'),
  ('general', 'Finally realized why my plant sits around doing nothing all day...', 'He loves his pot.'),
  ('general', 'Don''t look at the eclipse through a colander.', 'You''ll strain your eyes.'),
  ('general', 'I bought some shoes from a drug dealer.', 'I don''t know what he laced them with, but I was tripping all day!'),
  ('general', 'Why do chicken coops only have two doors?', 'Because if they had four, they would be chicken sedans'),
  ('general', 'What do you call a factory that sells passable products?', 'A satisfactory'),
  ('general', 'When a dad drives past a graveyard: Did you know that''s a popular cemetery?', 'Yep, people are just dying to get in there'),
  ('general', 'Why did the invisible man turn down the job offer?', 'He couldn''t see himself doing it'),
  ('general', 'How do you make holy water?', 'You boil the hell out of it'),
  ('general', 'I had a dream that I was a muffler last night.', 'I woke up exhausted!'),
  ('general', 'Why is peter pan always flying?', 'Because he neverlands'),
  ('programming', 'How do you check if a webpage is HTML5?', 'Try it out on Internet Explorer'),
  ('general', 'What do you call a cow with no legs?', 'Ground beef!'),
  ('general', 'I dropped a pear in my car this morning.', 'You should drop another one, then you would have a pair.'),
  ('general', 'Lady: How do I spread love in this cruel world?', 'Random Dude: [...💘]'),
  ('programming', 'A user interface is like a joke.', 'If you have to explain it then it is not that good.'),
  ('knock-knock', 'Knock knock. 
 Who''s there? 
 Hatch. 
 Hatch who?', 'Bless you!'),
  ('general', 'What do you call sad coffee?', 'Despresso.'),
  ('general', 'Why did the butcher work extra hours at the shop?', 'To make ends meat.'),
  ('general', 'Did you hear about the hungry clock?', 'It went back four seconds.'),
  ('general', 'Well...', 'That’s a deep subject.'),
  ('general', 'Did you hear the story about the cheese that saved the world?', 'It was legend dairy.'),
  ('general', 'Did you watch the new comic book movie?', 'It was very graphic!'),
  ('general', 'I started a new business making yachts in my attic this year...', 'The sails are going through the roof.'),
  ('general', 'I got hit in the head by a soda can, but it didn''t hurt that much...', 'It was a soft drink.'),
  ('general', 'I can''t tell if i like this blender...', 'It keeps giving me mixed results.'),
  ('general', 'I couldn''t get a reservation at the library...', 'They were fully booked.'),
  ('programming', 'I was gonna tell you a joke about UDP...', '...but you might not get it.'),
  ('programming', 'The punchline often arrives before the set-up.', 'Do you know the problem with UDP jokes?'),
  ('programming', 'Why do C# and Java developers keep breaking their keyboards?', 'Because they use a strongly typed language.'),
  ('general', 'What do you give to a lemon in need?', 'Lemonaid.'),
  ('general', 'Never take advice from electrons.', 'They are always negative.'),
  ('general', 'Hey, dad, did you get a haircut?', 'No, I got them all cut.'),
  ('general', 'What time is it?', 'I don''t know... it keeps changing.'),
  ('general', 'A weasel walks into a bar. The bartender says, "Wow, I''ve never served a weasel before. What can I get for you?"', 'Pop,goes the weasel.'),
  ('general', 'Bad at golf?', 'Join the club.'),
  ('general', 'Can a kangaroo jump higher than the Empire State Building?', 'Of course. The Empire State Building can''t jump.'),
  ('general', 'Can February march?', 'No, but April may.'),
  ('general', 'Can I watch the TV?', 'Yes, but don’t turn it on.'),
  ('general', 'Dad, can you put my shoes on?', 'I don''t think they''ll fit me.'),
  ('general', 'Did you hear about the bread factory burning down?', 'They say the business is toast.'),
  ('general', 'Did you hear about the chameleon who couldn''t change color?', 'They had a reptile dysfunction.'),
  ('general', 'Did you hear about the cheese factory that exploded in France?', 'There was nothing left but de Brie.'),
  ('general', 'Did you hear about the cow who jumped over the barbed wire fence?', 'It was udder destruction.'),
  ('general', 'Did you hear about the guy who invented Lifesavers?', 'They say he made a mint.'),
  ('general', 'Did you hear about the guy whose whole left side was cut off?', 'He''s all right now.'),
  ('general', 'Did you hear about the kidnapping at school?', 'It''s ok, he woke up.'),
  ('general', 'Did you hear about the Mexican train killer?', 'He had loco motives'),
  ('general', 'Did you hear about the new restaurant on the moon?', 'The food is great, but there’s just no atmosphere.'),
  ('general', 'Did you hear about the runner who was criticized?', 'He just took it in stride'),
  ('general', 'Did you hear about the scientist who was lab partners with a pot of boiling water?', 'He had a very esteemed colleague.'),
  ('general', 'Did you hear about the submarine industry?', 'It really took a dive...'),
  ('general', 'Did you hear that David lost his ID in prague?', 'Now we just have to call him Dav.'),
  ('general', 'Did you hear that the police have a warrant out on a midget psychic ripping people off?', 'It reads "Small medium at large."'),
  ('general', 'Did you hear the joke about the wandering nun?', 'She was a roman catholic.'),
  ('general', 'Did you hear the news?', 'FedEx and UPS are merging. They’re going to go by the name Fed-Up from now on.'),
  ('general', 'Did you hear the one about the guy with the broken hearing aid?', 'Neither did he.'),
  ('general', 'Did you know crocodiles could grow up to 15 feet?', 'But most just have 4.'),
  ('general', 'What do ghosts call their true love?', 'Their ghoul-friend'),
  ('general', 'Did you know that protons have mass?', 'I didn''t even know they were catholic.'),
  ('general', 'Did you know you should always take an extra pair of pants golfing?', 'Just in case you get a hole in one.'),
  ('general', 'Do I enjoy making courthouse puns?', 'Guilty'),
  ('general', 'Do you know where you can get chicken broth in bulk?', 'The stock market.'),
  ('general', 'Do you want a brief explanation of what an acorn is?', 'In a nutshell, it''s an oak tree.'),
  ('general', 'Ever wondered why bees hum?', 'It''s because they don''t know the words.'),
  ('general', 'Have you ever heard of a music group called Cellophane?', 'They mostly wrap.'),
  ('general', 'Have you heard of the band 1023MB?', 'They haven''t got a gig yet.'),
  ('general', 'Have you heard the rumor going around about butter?', 'Never mind, I shouldn''t spread it.'),
  ('general', 'How are false teeth like stars?', 'They come out at night!'),
  ('general', 'How can you tell a vampire has a cold?', 'They start coffin.'),
  ('general', 'How come a man driving a train got struck by lightning?', 'He was a good conductor.'),
  ('general', 'How come the stadium got hot after the game?', 'Because all of the fans left.'),
  ('general', 'How did Darth Vader know what Luke was getting for Christmas?', 'He felt his presents.'),
  ('general', 'How did the hipster burn the roof of his mouth?', 'He ate the pizza before it was cool.'),
  ('general', 'How do hens stay fit?', 'They always egg-cercise!'),
  ('general', 'How do locomotives know where they''re going?', 'Lots of training'),
  ('general', 'How do the trees get on the internet?', 'They log on.'),
  ('general', 'How do you find Will Smith in the snow?', ' Look for fresh prints.'),
  ('general', 'How do you fix a broken pizza?', 'With tomato paste.'),
  ('general', 'How do you fix a damaged jack-o-lantern?', 'You use a pumpkin patch.'),
  ('general', 'How do you get a baby alien to sleep?', ' You rocket.'),
  ('general', 'How do you get two whales in a car?', 'Start in England and drive West.'),
  ('general', 'How do you know if there’s an elephant under your bed?', 'Your head hits the ceiling!'),
  ('general', 'How do you make a hankie dance?', 'Put a little boogie in it.'),
  ('general', 'How good are you at Power Point?', 'I Excel at it.'),
  ('general', 'How do you organize a space party?', 'You planet.'),
  ('general', 'How do you steal a coat?', 'You jacket.'),
  ('general', 'How do you tell the difference between a crocodile and an alligator?', 'You will see one later and one in a while.'),
  ('general', 'How does a dyslexic poet write?', 'Inverse.'),
  ('general', 'How does a French skeleton say hello?', 'Bone-jour.'),
  ('general', 'How does a penguin build it’s house?', 'Igloos it together.'),
  ('general', 'How does a scientist freshen their breath?', 'With experi-mints!'),
  ('general', 'How does the moon cut his hair?', 'Eclipse it.'),
  ('general', 'How many apples grow on a tree?', 'All of them!'),
  ('general', 'How many bones are in the human hand?', 'A handful of them.'),
  ('general', 'How many hipsters does it take to change a lightbulb?', 'Oh, it''s a really obscure number. You''ve probably never heard of it.'),
  ('general', 'How many kids with ADD does it take to change a lightbulb?', 'Let''s go ride bikes!'),
  ('general', 'How many optometrists does it take to change a light bulb?', '1 or 2? 1... or 2?'),
  ('general', 'How many seconds are in a year?', '12. January 2nd, February 2nd, March 2nd, April 2nd.... etc'),
  ('general', 'How many South Americans does it take to change a lightbulb?', 'A Brazilian'),
  ('general', 'How many tickles does it take to tickle an octopus?', 'Ten-tickles!'),
  ('general', 'How much does a hipster weigh?', 'An instagram.'),
  ('general', 'How was the snow globe feeling after the storm?', 'A little shaken.'),
  ('general', 'Is the pool safe for diving?', 'It deep ends.'),
  ('general', 'Is there a hole in your shoe?', 'No… Then how’d you get your foot in it?'),
  ('general', 'What did the spaghetti say to the other spaghetti?', 'Pasta la vista, baby!'),
  ('general', 'What’s 50 Cent’s name in Zimbabwe?', '200 Dollars.'),
  ('general', 'Want to hear a chimney joke?', 'Got stacks of em! First one''s on the house'),
  ('general', 'Want to hear a joke about construction?', 'Nah, I''m still working on it.'),
  ('general', 'Want to hear my pizza joke?', 'Never mind, it''s too cheesy.'),
  ('general', 'What animal is always at a game of cricket?', 'A bat.'),
  ('general', 'What are the strongest days of the week?', 'Saturday and Sunday...the rest are weekdays.'),
  ('general', 'What biscuit does a short person like?', 'Shortbread. '),
  ('general', 'What cheese can never be yours?', 'Nacho cheese.'),
  ('general', 'What creature is smarter than a talking parrot?', 'A spelling bee.'),
  ('general', 'What did celery say when he broke up with his girlfriend?', 'She wasn''t right for me, so I really don''t carrot all.'),
  ('general', 'What did Michael Jackson name his denim store?', '   Billy Jeans!'),
  ('general', 'What did one nut say as he chased another nut?', ' I''m a cashew!'),
  ('general', 'What did one plate say to the other plate?', 'Dinner is on me!'),
  ('general', 'What did one snowman say to the other snow man?', 'Do you smell carrot?'),
  ('general', 'What did one wall say to the other wall?', 'I''ll meet you at the corner!'),
  ('general', 'What did Romans use to cut pizza before the rolling cutter was invented?', 'Lil Caesars'),
  ('general', 'What did the 0 say to the 8?', 'Nice belt.'),
  ('general', 'What did the beaver say to the tree?', 'It''s been nice gnawing you.'),
  ('general', 'What did the big flower say to the littler flower?', 'Hi, bud!'),
  ('general', 'What did the Buffalo say to his little boy when he dropped him off at school?', 'Bison.'),
  ('general', 'What did the digital clock say to the grandfather clock?', 'Look, no hands!'),
  ('general', 'What did the dog say to the two trees?', 'Bark bark.'),
  ('general', 'What did the Dorito farmer say to the other Dorito farmer?', 'Cool Ranch!'),
  ('general', 'What did the fish say when it swam into a wall?', 'Damn!'),
  ('general', 'What did the grape do when he got stepped on?', 'He let out a little wine.'),
  ('general', 'What did the judge say to the dentist?', 'Do you swear to pull the tooth, the whole tooth and nothing but the tooth?'),
  ('general', 'What did the late tomato say to the early tomato?', 'I’ll ketch up'),
  ('general', 'What did the left eye say to the right eye?', 'Between us, something smells!'),
  ('general', 'What did the mountain climber name his son?', 'Cliff.'),
  ('general', 'What did the ocean say to the beach?', 'Thanks for all the sediment.'),
  ('general', 'What did the ocean say to the shore?', 'Nothing, it just waved.'),
  ('general', 'Why don''t you find hippopotamuses hiding in trees?', 'They''re really good at it.'),
  ('general', 'What did the pirate say on his 80th birthday?', 'Aye Matey!'),
  ('general', 'What did the Red light say to the Green light?', 'Don''t look at me I''m changing!'),
  ('general', 'What did the scarf say to the hat?', 'You go on ahead, I am going to hang around a bit longer.'),
  ('general', 'What did the shy pebble wish for?', 'That she was a little boulder.'),
  ('general', 'What did the traffic light say to the car as it passed?', 'Don''t look I''m changing!'),
  ('general', 'What did the Zen Buddist say to the hotdog vendor?', 'Make me one with everything.'),
  ('general', 'What do birds give out on Halloween?', 'Tweets.'),
  ('general', 'What do I look like?', 'A JOKE MACHINE!?'),
  ('general', 'What do prisoners use to call each other?', 'Cell phones.'),
  ('general', 'What do vegetarian zombies eat?', 'Grrrrrainnnnnssss.'),
  ('general', 'What do you call a bear with no teeth?', 'A gummy bear!'),
  ('general', 'What do you call a bee that lives in America?', 'A USB.'),
  ('general', 'What do you call a boomerang that won''t come back?', 'A stick.'),
  ('general', 'What do you call a careful wolf?', 'Aware wolf.'),
  ('general', 'What do you call a cow on a trampoline?', 'A milk shake!'),
  ('general', 'What do you call a cow with no legs?', 'Ground beef.'),
  ('general', 'What do you call a cow with two legs?', 'Lean beef.'),
  ('general', 'What do you call a crowd of chess players bragging about their wins in a hotel lobby?', 'Chess nuts boasting in an open foyer.'),
  ('general', 'What do you call a dad that has fallen through the ice?', 'A Popsicle.'),
  ('general', 'What do you call a dictionary on drugs?', 'High definition.'),
  ('general', 'what do you call a dog that can do magic tricks?', 'a labracadabrador'),
  ('general', 'What do you call a droid that takes the long way around?', 'R2 detour.'),
  ('general', 'What do you call a duck that gets all A''s?', 'A wise quacker.'),
  ('general', 'What do you call a fake noodle?', 'An impasta.'),
  ('general', 'What do you call a fashionable lawn statue with an excellent sense of rhythmn?', 'A metro-gnome'),
  ('general', 'What do you call a fat psychic?', 'A four-chin teller.'),
  ('general', 'What do you call a fly without wings?', 'A walk.'),
  ('general', 'What do you call a girl between two posts?', 'Annette.'),
  ('general', 'What do you call a group of disorganized cats?', 'A cat-tastrophe.'),
  ('general', 'What do you call a group of killer whales playing instruments?', 'An Orca-stra.'),
  ('general', 'What do you call a monkey in a mine field?', 'A babooooom!'),
  ('general', 'What do you call a nervous javelin thrower?', 'Shakespeare.'),
  ('general', 'What do you call a pig that knows karate?', 'A pork chop!'),
  ('general', 'What do you call a pig with three eyes?', 'Piiig'),
  ('general', 'What do you call a pile of cats?', ' A Meowtain.'),
  ('general', 'What do you call a sheep with no legs?', 'A cloud.'),
  ('general', 'What do you call a troublesome Canadian high schooler?', 'A poutine.'),
  ('general', 'What do you call an alligator in a vest?', 'An in-vest-igator!'),
  ('general', 'What do you call an Argentinian with a rubber toe?', 'Roberto'),
  ('general', 'What do you call an eagle who can play the piano?', 'Talonted!'),
  ('general', 'What do you call an elephant that doesn’t matter?', 'An irrelephant.'),
  ('general', 'What do you call an old snowman?', 'Water.'),
  ('general', 'What do you call cheese by itself?', 'Provolone.'),
  ('general', 'What do you call corn that joins the army?', 'Kernel.'),
  ('general', 'What do you call someone with no nose?', 'Nobody knows.'),
  ('general', 'What do you call two barracuda fish?', ' A Pairacuda!'),
  ('general', 'What do you do on a remote island?', 'Try and find the TV island it belongs to.'),
  ('general', 'What do you do when you see a space man?', 'Park your car, man.'),
  ('general', 'What do you get hanging from Apple trees?', 'Sore arms.'),
  ('general', 'What do you get when you cross a bee and a sheep?', 'A bah-humbug.'),
  ('general', 'What do you get when you cross a chicken with a skunk?', 'A fowl smell!'),
  ('general', 'What do you get when you cross a rabbit with a water hose?', 'Hare spray.'),
  ('general', 'What do you get when you cross a snowman with a vampire?', 'Frostbite.'),
  ('general', 'What do you give a sick lemon?', 'Lemonaid.'),
  ('general', 'What does a clock do when it''s hungry?', 'It goes back four seconds!'),
  ('general', 'What does a female snake use for support?', 'A co-Bra!'),
  ('general', 'What does a pirate pay for his corn?', 'A buccaneer!'),
  ('general', 'What does an angry pepper do?', 'It gets jalapeño face.'),
  ('general', 'What happens to a frog''s car when it breaks down?', 'It gets toad.'),
  ('general', 'What happens when you anger a brain surgeon?', 'They will give you a piece of your mind.'),
  ('general', 'What has ears but cannot hear?', 'A field of corn.'),
  ('general', 'What is a centipedes''s favorite Beatle song?', ' I want to hold your hand, hand, hand, hand...'),
  ('general', 'What is a tornado''s favorite game to play?', 'Twister!'),
  ('general', 'What is a vampire''s favorite fruit?', 'A blood orange.'),
  ('general', 'What is a witch''s favorite subject in school?', 'Spelling!'),
  ('general', 'What is red and smells like blue paint?', 'Red paint!'),
  ('general', 'What is the difference between ignorance and apathy?', 'I don''t know and I don''t care.'),
  ('general', 'What is the hardest part about sky diving?', 'The ground.'),
  ('general', 'What is the leading cause of dry skin?', 'Towels'),
  ('general', 'What is the least spoken language in the world?', 'Sign Language'),
  ('general', 'What is the tallest building in the world?', 'The library, it’s got the most stories!'),
  ('general', 'What is this movie about?', 'It is about 2 hours long.'),
  ('general', 'What kind of award did the dentist receive?', 'A little plaque.'),
  ('general', 'What kind of bagel can fly?', 'A plain bagel.'),
  ('general', 'What kind of dinosaur loves to sleep?', 'A stega-snore-us.'),
  ('general', 'What kind of dog lives in a particle accelerator?', 'A Fermilabrador Retriever.'),
  ('general', 'What kind of magic do cows believe in?', 'MOODOO.'),
  ('general', 'What kind of music do planets listen to?', 'Nep-tunes.'),
  ('general', 'What kind of pants do ghosts wear?', 'Boo jeans.'),
  ('general', 'What kind of tree fits in your hand?', 'A palm tree!'),
  ('general', 'What lies at the bottom of the ocean and twitches?', 'A nervous wreck.'),
  ('general', 'What musical instrument is found in the bathroom?', 'A tuba toothpaste.'),
  ('general', 'What time did the man go to the dentist?', 'Tooth hurt-y.'),
  ('general', 'What type of music do balloons hate?', 'Pop music!'),
  ('general', 'What was a more important invention than the first telephone?', 'The second one.'),
  ('general', 'What was the pumpkin’s favorite sport?', 'Squash.'),
  ('general', 'What''s black and white and read all over?', 'The newspaper.'),
  ('general', 'What''s blue and not very heavy?', ' Light blue.'),
  ('general', 'What''s brown and sticky?', 'A stick.'),
  ('general', 'What''s orange and sounds like a parrot?', 'A Carrot.'),
  ('general', 'What''s red and bad for your teeth?', 'A Brick.'),
  ('general', 'What''s the best thing about elevator jokes?', 'They work on so many levels.'),
  ('general', 'What''s the difference between a guitar and a fish?', 'You can tune a guitar but you can''t "tuna"fish!'),
  ('general', 'What''s the difference between a hippo and a zippo?', 'One is really heavy, the other is a little lighter.'),
  ('general', 'What''s the difference between a seal and a sea lion?', 'An ion! '),
  ('general', 'What''s the worst part about being a cross-eyed teacher?', 'They can''t control their pupils.'),
  ('general', 'What''s the worst thing about ancient history class?', 'The teachers tend to Babylon.'),
  ('general', 'What’s brown and sounds like a bell?', 'Dung!'),
  ('general', 'What’s E.T. short for?', 'He’s only got little legs.'),
  ('general', 'What’s Forest Gump’s Facebook password?', '1forest1'),
  ('general', 'What’s the advantage of living in Switzerland?', 'Well, the flag is a big plus.'),
  ('general', 'What’s the difference between an African elephant and an Indian elephant?', 'About 5000 miles.'),
  ('general', 'When do doctors get angry?', 'When they run out of patients.'),
  ('general', 'When does a joke become a dad joke?', 'When it becomes apparent.'),
  ('general', 'When is a door not a door?', 'When it''s ajar.'),
  ('general', 'Where did you learn to make ice cream?', 'Sunday school.'),
  ('general', 'Where do bees go to the bathroom?', ' The BP station.'),
  ('general', 'Where do hamburgers go to dance?', 'The meat-ball.'),
  ('general', 'Where do rabbits go after they get married?', 'On a bunny-moon.'),
  ('general', 'Where do sheep go to get their hair cut?', 'The baa-baa shop.'),
  ('general', 'Where do you learn to make banana splits?', 'At sundae school.'),
  ('general', 'Where do young cows eat lunch?', 'In the calf-ateria.'),
  ('general', 'Where does batman go to the bathroom?', 'The batroom.'),
  ('general', 'Where does Fonzie like to go for lunch?', 'Chick-Fil-Eyyyyyyyy.'),
  ('general', 'Where does Napoleon keep his armies?', 'In his sleevies.'),
  ('general', 'Where was the Declaration of Independence signed?', 'At the bottom! '),
  ('general', 'Where’s the bin?', 'I haven’t been anywhere!'),
  ('general', 'Which side of the chicken has more feathers?', 'The outside.'),
  ('general', 'Who did the wizard marry?', 'His ghoul-friend'),
  ('general', 'Who is the coolest Doctor in the hospital?', 'The hip Doctor!'),
  ('general', 'Why are fish easy to weigh?', 'Because they have their own scales.'),
  ('general', 'Why are fish so smart?', 'Because they live in schools!'),
  ('general', 'Why are ghosts bad liars?', 'Because you can see right through them!'),
  ('general', 'Why are graveyards so noisy?', 'Because of all the coffin.'),
  ('general', 'Why are mummys scared of vacation?', 'They''re afraid to unwind.'),
  ('general', 'Why are oranges the smartest fruit?', 'Because they are made to concentrate. '),
  ('general', 'Why are pirates called pirates?', 'Because they arrr!'),
  ('general', 'Why are skeletons so calm?', 'Because nothing gets under their skin.'),
  ('general', 'Why can''t a bicycle stand on its own?', 'It''s two-tired.'),
  ('general', 'Why can''t you use "Beef stew"as a password?', 'Because it''s not stroganoff.'),
  ('general', 'Why can''t your nose be 12 inches long?', 'Because then it''d be a foot!'),
  ('general', 'Why can’t you hear a pterodactyl go to the bathroom?', 'The p is silent.'),
  ('general', 'Why couldn''t the kid see the pirate movie?', 'Because it was rated arrr!'),
  ('general', 'Why couldn''t the lifeguard save the hippie?', 'He was too far out, man.'),
  ('general', 'Why did Dracula lie in the wrong coffin?', 'He made a grave mistake.'),
  ('general', 'Why did Sweden start painting barcodes on the sides of their battleships?', 'So they could Scandinavian.'),
  ('general', 'Why did the A go to the bathroom and come out as an E?', 'Because he had a vowel movement.'),
  ('general', 'Why did the barber win the race?', 'He took a short cut.'),
  ('general', 'Why did the belt go to prison?', 'He held up a pair of pants!'),
  ('general', 'Why did the burglar hang his mugshot on the wall?', 'To prove that he was framed!'),
  ('general', 'Why did the chicken get a penalty?', 'For fowl play.'),
  ('general', 'Why did the Clydesdale give the pony a glass of water?', 'Because he was a little horse!'),
  ('general', 'Why did the coffee file a police report?', 'It got mugged.'),
  ('general', 'Why did the cookie cry?', 'Because his mother was a wafer so long'),
  ('general', 'Why did the cookie cry?', 'It was feeling crumby.'),
  ('general', 'Why did the cowboy have a weiner dog?', 'Somebody told him to get a long little doggy.'),
  ('general', 'Why did the fireman wear red, white, and blue suspenders?', 'To hold his pants up.'),
  ('general', 'Why did the girl smear peanut butter on the road?', 'To go with the traffic jam.'),
  ('general', 'Why did the half blind man fall in the well?', 'Because he couldn''t see that well!'),
  ('general', 'Why did the house go to the doctor?', 'It was having window panes.'),
  ('general', 'Why did the kid cross the playground?', 'To get to the other slide.'),
  ('general', 'Why did the man put his money in the freezer?', 'He wanted cold hard cash!'),
  ('general', 'Why did the man run around his bed?', 'Because he was trying to catch up on his sleep!'),
  ('general', 'Why did the melons plan a big wedding?', 'Because they cantaloupe!'),
  ('general', 'Why did the octopus beat the shark in a fight?', 'Because it was well armed.'),
  ('general', 'Why did the opera singer go sailing?', 'They wanted to hit the high Cs.'),
  ('general', 'Why did the scarecrow win an award?', 'Because he was outstanding in his field.'),
  ('general', 'Why did the tomato blush?', 'Because it saw the salad dressing.'),
  ('general', 'Why did the tree go to the dentist?', 'It needed a root canal.'),
  ('general', 'Why did the worker get fired from the orange juice factory?', 'Lack of concentration.'),
  ('general', 'Why didn''t the number 4 get into the nightclub?', 'Because he is 2 square.'),
  ('general', 'Why didn’t the orange win the race?', 'It ran out of juice.'),
  ('general', 'Why didn’t the skeleton cross the road?', 'Because he had no guts.'),
  ('general', 'Why do bananas have to put on sunscreen before they go to the beach?', 'Because they might peel!'),
  ('general', 'Why do bears have hairy coats?', 'Fur protection.'),
  ('general', 'Why do bees have sticky hair?', 'Because they use honey combs!'),
  ('general', 'Why do bees hum?', 'Because they don''t know the words.'),
  ('general', 'Why do birds fly south for the winter?', 'Because it''s too far to walk.'),
  ('general', 'Why do choirs keep buckets handy?', 'So they can carry their tune'),
  ('general', 'Why do crabs never give to charity?', 'Because they’re shellfish.'),
  ('general', 'Why do ducks make great detectives?', 'They always quack the case.'),
  ('general', 'Why do mathematicians hate the U.S.?', 'Because it''s indivisible.'),
  ('general', 'Why do pirates not know the alphabet?', 'They always get stuck at "C".'),
  ('general', 'Why do pumpkins sit on people’s porches?', 'They have no hands to knock on the door.'),
  ('general', 'Why do scuba divers fall backwards into the water?', 'Because if they fell forwards they’d still be in the boat.'),
  ('general', 'Why do trees seem suspicious on sunny days?', 'Dunno, they''re just a bit shady.'),
  ('general', 'Why do valley girls hang out in odd numbered groups?', 'Because they can''t even.'),
  ('general', 'Why do wizards clean their teeth three times a day?', 'To prevent bat breath!'),
  ('general', 'Why do you never see elephants hiding in trees?', 'Because they''re so good at it.'),
  ('general', 'Why does a chicken coop only have two doors?', 'Because if it had four doors it would be a chicken sedan.'),
  ('general', 'Why does a Moon-rock taste better than an Earth-rock?', 'Because it''s a little meteor.'),
  ('general', 'Why does it take longer to get from 1st to 2nd base, than it does to get from 2nd to 3rd base?', 'Because there’s a Shortstop in between!'),
  ('general', 'Why does Norway have barcodes on their battleships?', 'So when they get back to port, they can Scandinavian.'),
  ('general', 'Why does Superman get invited to dinners?', 'Because he is a Supperhero.'),
  ('general', 'Why does Waldo only wear stripes?', 'Because he doesn''t want to be spotted.'),
  ('programming', 'Knock-knock.', 'A race condition. Who is there?'),
  ('programming', 'What''s the best part about TCP jokes?', 'I get to keep telling them until you get them.'),
  ('programming', 'A programmer puts two glasses on his bedside table before going to sleep.', 'A full one, in case he gets thirsty, and an empty one, in case he doesn’t.'),
  ('programming', 'There are 10 kinds of people in this world.', 'Those who understand binary, those who don''t, and those who weren''t expecting a base 3 joke.'),
  ('general', 'Two guys walk into a bar . . .', 'The first guy says "Ouch!" and the second says "Yeah, I didn''t see it either."'),
  ('programming', 'What did the router say to the doctor?', 'It hurts when IP.'),
  ('programming', 'An IPv6 packet is walking out of the house.', 'He goes nowhere.'),
  ('programming', 'A DHCP packet walks into a bar and asks for a beer.', 'Bartender says, "here, but I’ll need that back in an hour!"'),
  ('programming', '3 SQL statements walk into a NoSQL bar. Soon, they walk out', 'They couldn''t find a table.'),
  ('general', 'I saw a nice stereo on Craigslist for $1. Seller says the volume is stuck on ‘high’', 'I couldn’t turn it down.'),
  ('programming', 'What’s the object-oriented way to become wealthy?', 'Inheritance.'),
  ('general', 'What do you call a bee that can''t make up its mind?', 'A maybe.'),
  ('general', 'Why was Cinderalla thrown out of the football team?', 'Because she ran away from the ball.'),
  ('general', 'What kind of music do welders like?', 'Heavy metal.'),
  ('general', 'Why are “Dad Jokes” so good?', 'Because the punchline is apparent.'),
  ('programming', 'Java developers wear glasses.', 'Because they can''t C#.'),
  ('programming', 'Why dot net developers don''t wear glasses?', 'Because they see sharp.'),
  ('general', 'Why is seven bigger than nine?', 'Because seven ate nine.'),
  ('dad', 'Why do fathers take an extra pair of socks when they go golfing?', 'In case they get a hole in one!'),
  ('general', 'What do you call a suspicious looking laptop?', 'Asus'),
  ('programming', 'What did the Java code say to the C code?', 'You''ve got no class.'),
  ('programming', 'What is the most used language in programming?', 'Profanity.'),
  ('programming', 'Why do programmers always get Christmas and Halloween mixed up?', 'Because DEC 25 = OCT 31'),
  ('programming', 'What goes after USA?', 'USB.'),
  ('dad', 'Why don''t eggs tell jokes?', 'Because they would crack each other up.'),
  ('general', 'How do you make the number one disappear?', 'Add the letter G and it’s “gone”!'),
  ('general', 'My older brother always tore the last pages of my comic books, and never told me why.', 'I had to draw my own conclusions.'),
  ('general', 'The Sergeant-Major growled at the young soldier: I didn’t see you at camouflage training this morning.', 'Thank you very much, sir.'),
  ('general', 'Why does Waldo only wear stripes?', 'Because he doesn''t want to be spotted.'),
  ('programming', 'A male developer often gets called as a Dev, then what would you call a female developer?.', 'Devi.'),
  ('general', 'Why did the kid throw the watch out the window?', 'So time would fly.'),
  ('programming', 'Where did the API go to eat?', 'To the RESTaurant.'),
  ('food', 'Why did the rooster cross the road?', 'He heard that the chickens at KFC were pretty hot.');